version: '3.8'

services:
  backend:
    container_name: latish44-backend
    build: ./Backend
    ports:
      - "3038:3038"
    depends_on:
      - postgres
    environment:
      - PGUSER=postgres
      - PGPASSWORD=admin123
      - PGHOST=postgres
      - PGPORT=5432
      - PGDATABASE=jobflow_db

  job-apply:
    container_name: latish44-job-apply
    build: ./job-apply
    ports:
      - "8071:80"
    depends_on:
      - backend

  job-post:
    container_name: latish44-job-post
    build: ./job-post
    ports:
      - "8072:80"
    depends_on:
      - backend

  postgres:
    container_name: latish44-postgres
    image: postgres:13
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: jobflow_db
    volumes:
      - pgdata44:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata44:

